name: 'Netlify Dev Builds'

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    environment:
      name: Development
      url: ${{ env.NETLIFY_PREVIEW_URL }}

    env:
      NEXT_PUBLIC_BUILDER_API_KEY: ${{ secrets.NEXT_PUBLIC_BUILDER_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: npm run build

      # Sets the branch name as environment variable
      - uses: nelonoel/branch-name@v1.0.1
      - uses: artabr/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          deploy_alias: ${{ env.BRANCH_NAME }}
          build_directory: '.next'
          functions_directory: '.netlify/functions'
          install_command: 'bun install'
          command_extra_flags: "--context branch-deploy"

      # Creates a status check with link to preview
      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
          target_url: ${{ env.NETLIFY_PREVIEW_URL }}
